import Head from 'next/head'
import '../styles/globals.css'
import NavBar from '../components/NavBar';

function MyApp({ Component, pageProps }) {
  
  return (
    <div>
  <Head>
        <title>project5</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <p>this one should appear everywhere</p>
    <NavBar/>
  <Component {...pageProps} />
  </div>
  );
}

export default MyApp
