import Head from 'next/head';
import '../styles/globals.css';
import '../styles/Home.module.css';
import '../styles/styles.css'
import NavBar from '../components/NavBar';


function MyApp({ Component, pageProps }) {
  //here we console.log our 'app' variable when checking if any env variables are ok
  
  return (
    <div>
  <Head>
        <title>project5nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {/* <p>this one should appear everywhere</p> */}
    <NavBar/>
  <Component {...pageProps} />
  </div>
  );
}

export default MyApp
